[package]
name = "curie-util"
version = "0.0.2-SNAPSHOT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trie-rs = "0.1.1"


[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "trie_curie_util"
harness = false
